version: '2'
services:
  first-drupal-mysql:
    container_name: first-drupal-mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ../sites-databases/first-drupal:/var/lib/mysql
    networks:
      - dockercompose
    command: mysqld --max_allowed_packet=64M
    restart: always
  first-drupal:
    container_name: first-drupal
    image: codekoalas/drupal8:permissionsFix
    environment:
      VIRTUAL_HOST: .first-drupal.localhost
      #GIT_HOSTS: "IP url" it was hard coded to our internal gitlab removed for safety
      GIT_REPO: https://github.com/fabean/first-drupal.git
      GIT_BRANCH: 8.x
      MYSQL_SERVER: mysql
      MYSQL_DATABASE: drupal
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      DRUPAL_BASE_URL: http://first-drupal.localhost
      DRUPAL_TRUSTED_HOSTS: first-drupal\.localhost$$
      DRUPAL_HTTPS: "off"
      APACHE_DOCROOT: /var/www/site/docroot
      PRODUCTION: "false"
      #SESMailHub: mail-relay.ckdev.io
      #LOCAL: "true"
    volumes:
      - ../sites-files/first-drupal:/mnt/site-files
      - ./:/var/www/site
      #- first-drupal-files-sync:/mnt/sites-files
      #- first-drupal-sync:/var/www/site
    networks:
      - dockercompose
    links:
      - first-drupal-mysql:mysql
    # extra_hosts:
      #- "xdebug:192.168.237.237"
    restart: always
networks:
  dockercompose:
    external:
      name: docker-compose_dockercompose
#volumes:
#  first-drupal-sync:
#    external: true
#  first-drupal-files-sync:
#    external: true
#  first-drupal-mysql-sync:
#    external: true
