features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://Koala_climbing_tree_copy_2.jpg'
favicon:
  use_default: true
